### PR TITLE
Cleaning up logic in Parser

### PR DESCRIPTION
**Pull request by fpruitt**
## Purpose

This PR reduces redundancy and eliminates the jobs of a number of if/elif/else blocks in the parser. What could be more American, nay, more Trumpian, than pairing down and eliminating the useless?

### CODE REVIEW

**Comment by CryoBrown** [comment]
Oh this is good. The merge is gunna be hard on sam since I also just modified the parser pretty heavily though.

**Comment by fpruitt** [comment]
No conflicts currently, but if I need to work through a merge I definitely will :+1:

**Comment by samshadwell** [comment]
First pass of trying to go through the merge didn't work (we're getting the "required field "lineno" missing from expr"). Just pushed my attempted merge to a branch. I'll look at this again later.

**Comment by samshadwell** [comment]
This is after merging Chris's PR, and trying to merge this one into that. Chris's PR alone worked.

**Comment by samshadwell** [comment]
I'll probably do more work on this later, after I eat and do my actual homework and stuff.

**Pull request merged**
