### PR TITLE
Standard Input

### PR DESCRIPTION
**Pull request by 18padx08**
Added Standard Input ("hears")
Added support for boolean logic (somehow and and or did not work)
Added support for brace like structures in brace like structures (e.g. if in while loop)
Added a "floor" function (conversion from float to int)
Added an algorithm for prime test in test file

Added some allowed words

Fixed a bug in if else sturcture

### CODE REVIEW

**Comment by samshadwell** [comment]
:+1: Awesome pull request.

**Comment by 18padx08** [comment]
awesome idea^^

**Comment by TheInitializer** [comment]
How do I use the standard input?

**Comment by 18padx08** [comment]
Try: $varname hears you (last word will be ignored)
That should save the input from stdin into $varname.

**Pull request merged**
