### PR TITLE
ban arabic numerals

### PR DESCRIPTION
**Pull request by fredkneeland-wf**
No muslims allowed!  Numbers should be converted to english letters!

### CODE REVIEW

**Comment by fredkneeland-wf** [comment]
Addresses: https://github.com/samshadwell/TrumpScript/pull/159

**Comment by killvung** [comment]
Dude 
do you know that arabic number is invented by Indians?

**Comment by MoxieBaez** [comment]
Lol, that was humorous albeit short sighted. Humor is the best medicine. I'm a woman should I be allowed to commit? Lol

**Comment by samshadwell** [comment]
This doesn't actually change what's allowed, you're simply changing the intermediate representation of the tokens to use nonsensical strings instead of numeric types. This breaks things like arithmetic operators (which you can demo by running the 99-bottles test file).

**Pull request closed without merging**
