### PR TITLE
Add Part (b) assignment section in README

### PR DESCRIPTION
**Pull request by luisRojas29**
Ok, I think this is the correct place to make the pull request on this branch... regards...

### CODE REVIEW

**Comment by bruceLeeO** [comment]
Hello @samshadwell this is Leo (@bruceLeeO) and my fellow contributor @luisRojas29 and we are sending you this pull request as part of our collaboration project assignment at Learn.ModernDeveloper.  We are learning about GitHub and its inner workings and as part of our assignment we are to fork a popular, remarkable repository like yours and learn as much as we can about the technology and then offer to make a contribution to the already outstanding README file.  

We are to offer two parts in the README file: 1) to write a _Clear, Easy to Understand Introduction for TrumpScript_ repository and 2) to include a _What is TrumpScript Use For and When to Use It_ section in the README.  

Our aim is to provide visitor a clear, easy-to-comprehend introduction

**Comment by bruceLeeO** [comment]
Hello @samshadwell this is Leo (@bruceLeeO) and my fellow contributor @luisRojas29 and we are sending you this pull request as part of our collaboration project assignment at [Learn.ModernDeveloper](https://learn.modern-developer.com/). We are learning about GitHub and its inner workings and as part of our assignment we are to fork a popular, remarkable repository like yours and learn as much as we can about the technology and then offer to make a contribution to the already outstanding README file.

We are to offer two parts in the README file: 1) to write a _Clear, Easy to Understand Introduction for TrumpScript_ repository and 2) to include a _What is TrumpScript Use For and When to Use It_ section in the README file.

Our aim is to provide visitor a clear, easy-to-comprehend introduction for TrumpScript and a new section that briefly describes What TrumpScript is use for and when to use it .  Seasoned developer, new programmers, and even nontechnical visitor will benefit from the clear language, exposing TrumpScript to a broader range of users.  

We have learned a great deal and we strive for excellence. We are very honored to have worked through your TrumpScript repository and we hope you find our proposed contribution beneficial.

Leo and Luis

**Comment by samshadwell** [comment]
Sorry guys, I don't think this really adds much. I appreciate that you're trying to contribute, but this PR doesn't really align with what we're trying to do. I feel like this is mostly just repeating the other information we've already got in the README, and is even a bit misleading. Like, it seems to imply that it won't throw errors, and that you can ignore the language syntax, which simply isn't true.

**Comment by bruceLeeO** [comment]
That's fine Sam.  This has been a great learning experience for us and we appreciate your feedback.

**Pull request closed without merging**
