### PR TITLE
Update allowed_words.py

### PR DESCRIPTION
**Pull request by novellizator**
added 'muslim' and 'muslims'

### CODE REVIEW

**Comment by alir** [comment]
Methinks it'd make more sense if this were in "disallowed_words.py"

[Le Trump Quote](http://i.imgur.com/Z5WPKam.jpg)

**Comment by novellizator** [comment]
mexicans are there as well - he uses both.

Although, thinking about it, perhaps both should be moved, what do you think?

**Comment by alir** [comment]
Hmm... makes sense.
But I dunno.

:confused:

**Comment by CryoBrown** [comment]
We live in very uncertain times

**Comment by samshadwell** [comment]
See a76f078

**Comment by novellizator** [comment]
God, when I first wrote this I never believed this (and by this I mean him) will ever become close to a thing

**Pull request closed without merging**
