### PR TITLE
correct naming of rosie o'donnel

### PR DESCRIPTION
**Pull request by fredkneeland-wf**
Don't leave doubt in anyones mind about who Rosie O'donnel is!

### CODE REVIEW

**Comment by fredkneeland-wf** [comment]
Fixes: https://github.com/samshadwell/TrumpScript/issues/154

**Comment by killvung** [comment]
Have you tested it before you pr?

**Comment by samshadwell** [comment]
Please submit a test file along with this PR to show it working.

**Comment by samshadwell** [comment]
See a76f078

**Pull request closed without merging**
